# Variables needed for this script are:

# Case 1: Stored on Travis Settings
  # For all environments:
    # - DOCKER_CI_REPO_NAME
    # - DOCKER_USERNAME
    # - DOCKER_PASSWORD

  #For dev environment:
    # - AWS_ACCOUNT_USER_ID_DEV
    # - AWS_ACCOUNT_SECRET_DEV
    # - AWS_PROFILE_DEV <-- is this needed?

  #For Prod environment:
    # - AWS_ACCOUNT_USER_ID_PROD
    # - AWS_ACCOUNT_SECRET_PROD
    # - AWS_PROFILE_PROD <-- is this needed?

  #For Demo environment:
    # - AWS_ACCOUNT_USER_ID_DEMO
    # - AWS_ACCOUNT_SECRET_DEMO
    # - AWS_PROFILE_DEMO <-- is this needed?

# Case 2: Created when Travis CI runs
    # - IMAGE_TAG

sudo: required
language: generic
services:
  - docker

env:
  global:
    - IMAGE_TAG=${TRAVIS_COMMIT::7}

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -o $HOME/.local/bin/ecs-cli
    https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest &&
    chmod +x $HOME/.local/bin/ecs-cli

install:
  - docker build -t $DOCKER_CI_REPO_NAME .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t $DOCKER_CI_REPO_NAME:latest .
  - docker tag $DOCKER_CI_REPO_NAME:latest $DOCKER_CI_REPO_NAME:$IMAGE_TAG
  - docker push $DOCKER_CI_REPO_NAME:latest
  - docker push $DOCKER_CI_REPO_NAME:$IMAGE_TAG

matrix:
  include:
    - env: DEPLOY=dev
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEV
            AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEV
            ./deploy.sh dev
        on:
          branch: master
    - env: DEPLOY=demo
      if: tag IS present
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_DEMO
            AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_DEMO
            ./deploy.sh demo
        on:
          tags: true
    - env: DEPLOY=prod
      if: tag IS present
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - AWS_ACCESS_KEY_ID=$AWS_ACCOUNT_USER_ID_PROD
            AWS_SECRET_ACCESS_KEY=$AWS_ACCOUNT_SECRET_PROD
            ./deploy.sh prod
        on:
          tags: true
