# we need to update the hardcoded variables here

version: '2'
services:
    bugzilla:
        # This is a hardoded variable (need to optimize that)
        image: uneetins/bugzilla-customisation:latest
        # END This is a hardoded variable (need to optimize that)
        mem_reservation: 1g
        mem_limit: 3g  # assuming a t2.medium host with 4GB of RAM
        ports:
            - 80:80
        environment:
            SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
            SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
            SES_VERIFIED_SENDER: ${SES_VERIFIED_SENDER}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PARAMS_URL: ${PARAMS_URL}
        logging:
            driver: awslogs
            options:
                # This is a hardoded variable (need to optimize that)
                awslogs-region: ap-southeast-1
                awslogs-group: bugzilla
                # END This is a hardoded variable (need to optimize that)
                awslogs-stream-prefix: ecs
