version: '2'
services:
    bugzilla:
        image: uneet/bugzilla-customisation
        restart: on-failure
        ports:
            - 8081:80
        environment: # Setup by local .env file
            SES_SMTP_USERNAME: ${SES_SMTP_USERNAME}
            SES_SMTP_PASSWORD: ${SES_SMTP_PASSWORD}
            SES_VERIFIED_SENDER: ${SES_VERIFIED_SENDER}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PARAMS_URL: ${PARAMS_URL}
        depends_on:
            - db

    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            # - /home/hendry/unee-t/bugzilla-customisation/backup/localhost-backup-1568357621.sql:/docker-entrypoint-initdb.d/main.sql
            - ./sql-conf.d:/etc/mysql/conf.d

    adminer:
        image: adminer
        ports:
            - 8082:8080
        depends_on:
            - db

    mefe: #aka frontend, CASE_HOST
        image: uneet/frontend
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - mongo
            - bugzilla
        environment:
            MONGO_URL: mongodb://mongo:27017/meteor
            ROOT_URL: http://mefe:3000
            BUGZILLA_URL: http://bugzilla
            API_ACCESS_TOKEN: ${API_ACCESS_TOKEN}
            BUGZILLA_ADMIN_KEY: ${BUGZILLA_ADMIN_KEY}
            CLOUDINARY_URL: ${CLOUDINARY_URL}
            CLOUDINARY_PRESET: ${CLOUDINARY_PRESET}
            APIENROLL_LAMBDA_URL: http://localhost:4000
            UNIT_CREATE_LAMBDA_URL: http://unit:4001
            INVITE_LAMBDA_URL: http://invite:4002

    mongo:
        image: mongo
        ports:
            - 27017:27017

    apienroll:
        image: uneet/apienroll
        ports:
            - 4000:9000
        environment:
            PORT: 9000
            MYSQL_HOST: db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            API_ACCESS_TOKEN: ${API_ACCESS_TOKEN}

    unit:
        image: uneet/unit
        ports:
            - 4001:9000
        environment:
            PORT: 9000
            MYSQL_HOST: db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            API_ACCESS_TOKEN: ${API_ACCESS_TOKEN}

    invite:
        image: uneet/invite
        ports:
            - 4002:9000
        environment:
            PORT: 9000
            MYSQL_HOST: db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            API_ACCESS_TOKEN: ${API_ACCESS_TOKEN}
            CASE_HOST: http://mefe:3000
